name: Simple Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch: # Add this block for manual triggering
    inputs:
      parameter_name: # Define any input parameters you want to provide
        description: Description of the input parameter
        required: true

jobs:
  simple:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"
